### ISSUE TITLE
Tests are broken with jekyll 3.5.1

### ISSUE THREAD

**Issue by jseppi** [18F/guides-style#100]
Ref this recent build of `master` https://travis-ci.org/18F/guides-style/jobs/258198953 and https://github.com/18F/guides-style/pull/99#issuecomment-318414354

```sh
NoMethodError: undefined method `frontmatter_defaults' for #<GuidesStyle18F::DummySite:0x007fd01b175870>
```

**Comment by afeld** [comment]
Fixed by #101.
