### ISSUE TITLE
Move jQuery from CDN to self hosted in repo

### ISSUE THREAD

**Issue by juliaelman** [18F/guides-style#19]
There are several reasons why I am making this recommendation, but want to focus on two primary reasons why we should move away from CDN for jQuery: security and reliability. We want to be able to have control over our resources in case of points of failure, code upgrades or other issues that may arise from these scripts. This is a fairly menial task and one that will have great benefits in the long term.

**Comment by mbland** [comment]
Sounds good to me.

**Comment by mbland** [comment]
This and #20 are included in [`guides_style_18f v0.1.9`](https://rubygems.org/gems/guides_style_18f), which has been deployed to:

- https://pages.18f.gov/guides-template/
- https://pages-staging.18f.gov/guides-template/
- https://pages-internal.18f.gov/guides-template/
