### ISSUE TITLE
allow for mismatched page titles and nav bar text

### ISSUE THREAD

**Issue by afeld** [18F/guides-style#31]
In [Before You Ship](https://pages.18f.gov/before-you-ship/), we have some pages with very long titles (for better or worse). To not overflow the sidebar, I've been maintaining the `navigation` list in the [`_config.yml`](https://github.com/18F/before-you-ship/blob/18f-pages/_config.yml) manually with shorter versions of the titles (in the `text` attribute). For example: the [ATO checklist](https://pages.18f.gov/before-you-ship/ato/checklist/) page has a `title` of `ATO Checklist`, but since it's nested under the `ATOs` item in the sidebar, I shortened it to `Checklist`.

![ato_checklist_-_before_you_ship](https://cloud.githubusercontent.com/assets/86842/12311268/0ffc7a2c-ba24-11e5-8f7f-aae56c7cb63e.png)

The problem is that [the sidebar template](https://github.com/18F/guides-style/blob/79a515554014b8d3489722fdcd9c4e456a1bb8bf/lib/guides_style_18f/includes/sidebar.html#L6) uses the `page.title` to highlight that item, which in these cases, don't match. I have a couple of proposals:

* Support the equivalent of Hugo's [`linktitle`](https://gohugo.io/extras/menus/#nesting:4044c7430755cd64e5b7c48e836cea57), which allows the page title to be overridden for the sidebar
* Decide whether things like nav bar order should be managed in the `_config.yml` (which I believe is currently the case) vs. the YAML metadata (using the equivalent of Hugo's [`weight`](https://gohugo.io/content/ordering/) attribute)
    * If the former, maybe we can de-dupe the information that's in both places, i.e. maybe make it so only the `url` attribute is needed

Hope that all makes sense...? Thoughts?

/cc @leahbannon

**Comment by mbland** [comment]
I could very easily support `navtitle` front matter that gets used instead if present. In fact, expect a PR. (Also, if you want to review and merge #30 while you're at it, I'd be much obliged.)

Regarding whether this should live in `_config.yml` or in, say `_data/nav.yml`, that's orthogonal. We kept it in `_config.yml` because that's what [DOCter](https://github.com/cfpb/docter) had from the start.

**Comment by afeld** [comment]
> Regarding whether this should live in `_config.yml` or in, say `_data/nav.yml`, that's orthogonal

Sorry, I meant having the nav generated in `_config.yml` (as it does now) vs. managing everything nav-related in the frontmatter of each page (as Hugo does).
