### ISSUE TITLE
when a top-level navigation item is active, expand it's list of nested pages

### ISSUE THREAD

**Issue by afeld** [18F/guides-style#40]
The [Before You Ship](https://pages.18f.gov/before-you-ship/) sidebar currently looks like this:

![screen shot 2016-01-27 at 1 16 10 pm](https://cloud.githubusercontent.com/assets/86842/12623440/35902f70-c4f8-11e5-8888-f868551befd6.png)

When the user is on the ATO page, I think it would make sense to expand that navigation item in the accordion so that it's list of child pages are shown. Thoughts?

**Comment by mbland** [comment]
Sure, that would be an easy tweak. I'll try to get to it later today or tomorrow.
