### ISSUE TITLE
Determine content for footer

### ISSUE THREAD

**Issue by hbillings** [18F/guides-style#81]
Using the [medium footer](https://standards.usa.gov/components/footers/). Needs the updated logo and whatever text we decide should be in there.

**Comment by hbillings** [comment]
Currently looks like this. I'm kinda meh on it (and "Hosted by 18F" in the top ribbon just seems misplaced). <img width="1206" alt="screen shot 2017-03-31 at 10 58 29 am" src="https://cloud.githubusercontent.com/assets/509309/24560701/026ff610-1601-11e7-8a3a-865434ca6bb7.png">

**Comment by wslack** [comment]
Do we need the medium or can we use small? It should say "hosted by Federalist" and link to https://federalist.fr.cloud.gov/.

**Comment by wslack** [comment]
and we can use the 18F logo I think - since this style was only used on 18F guides, though it would be nice if people could customize.

**Comment by wslack** [comment]
https://pages.18f.gov/brand/

**Comment by wslack** [comment]
I do like linking to the theme repo as well.

**Comment by hbillings** [comment]
This is super helpful! Lemme bust up what the small footer would look like and post a screenshot here.

**Comment by hbillings** [comment]
Okay, here's what the slim footer with the logo looks like: <img width="1066" alt="screen shot 2017-03-31 at 12 47 39 pm" src="https://cloud.githubusercontent.com/assets/509309/24564746/46e06e9c-1610-11e7-90d8-7fcb6fc76f34.png">

**Comment by wslack** [comment]
@hbillings up to you, but I would just destroy the footer part with the logo so as to save space.

**Comment by hbillings** [comment]
@wslack If you still want the logo in there, I can do something like this:
<img width="1023" alt="screen shot 2017-03-31 at 2 59 06 pm" src="https://cloud.githubusercontent.com/assets/509309/24569891/a6552e66-1625-11e7-8386-021eb72cff25.png">

or this:
<img width="884" alt="screen shot 2017-03-31 at 3 20 43 pm" src="https://cloud.githubusercontent.com/assets/509309/24569896/ab72a72a-1625-11e7-90a9-05f76e5440e5.png">

**Comment by wslack** [comment]
The top one looks awesome!
