### ISSUE TITLE
Update version of Jekyll used

### ISSUE THREAD

**Issue by hbillings** [18F/guides-style#84]
I'm totally not sure where this is in the codebase, but I know it relies on a really old version of Jekyll _somewhere_. That's no gud.

**Comment by hbillings** [comment]
http://guides.rubygems.org/patterns/#declaring-dependencies

**Comment by hbillings** [comment]
So, if I'm reading [this issue](https://github.com/18F/jekyll_pages_api_search/issues/37) correctly, the version of Jekyll can't exceed 3.1 if we want it to be compatible with the search plugin. Sad sad sad face.

It looks like there is no version of Jekyll specified in the `guides-style` plugin after all -- `gemspec` merely says `s.add_runtime_dependency 'jekyll'` without a version. Some guides, however, do seem to have their versions locked to 3.1.0 because of the aforementioned search issue.

**Comment by afeld** [comment]
Closed by #109.
