### ISSUE TITLE
Add backup gem admin(s)

### ISSUE THREAD

**Issue by arowla** [18F/guides-style#9]
This afternoon, I helped @wslack debug an issue with the gem that was causing problems for https://pages.18f.gov/intake, but then I didn't have permission to run `rake release` to cut the new gem version. Gems probably ought to have backup admins.

**Comment by mbland** [comment]
@arowla do you have a Rubygems account? If so, under what email account? Feel free to send a PR to add yourself to `guides_style_18f.gemspec` as well (adding yourself to `authors` and `email`).

**Comment by mbland** [comment]
Just cut v0.1.2, BTW. cc: @wslack
